# pubspec.yaml

name: guitar_notebook
description: "Aplicativo para auxiliar na prática de violão."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  bot_toast: ^4.1.3
  drift: ^2.28.1
  drift_flutter: ^0.2.5
  flutter:
    sdk: flutter
  
  flutter_card_swiper: ^7.0.2
  flutter_guitar_chord: ^0.0.3
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  
  flutter_native_splash: ^2.4.6
  flutter_slidable: ^3.1.2
  freezed: ^2.5.2
  google_fonts: ^6.2.1
  intl: 0.20.2
  introduction_screen: ^3.1.17
  json_annotation: ^4.9.0
  lottie: ^3.1.3
  package_info_plus: ^8.0.2
  path_provider: ^2.1.4
  provider: ^6.1.5
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.9
  drift_dev: ^2.19.1
  rename: ^3.1.0

flutter_native_splash:
  color: "#003366"
  image: assets/icon/icon_tr.png
  android_12:
    color: "#003366"
    image: assets/icon/icon_tr.png

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/animations/
    - assets/images/
    - assets/data/
flutter_intl:
  enabled: true