# pubspec.yaml

name: guitar_learner
description: "Aplicativo para auxiliar na prática de violão."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  bot_toast: ^4.1.3
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter
  
  freezed: ^2.5.2
  google_fonts: ^6.2.1
  intl: ^0.18.1
  json_annotation: ^4.9.0
  lottie: ^3.1.3
  package_info_plus: ^8.0.2
  provider: ^6.1.5
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/animations/
flutter_intl:
  enabled: true